name: Scheduled Job

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run a Script
        run: echo "Hello, this is a scheduled GitHub Actions job!"
